### PR TITLE
Add automated testing for `pytest` through GitHub Actions

### LINKED ISSUE #53: Add automated tests for `pytest` through GitHub Actions
This issue outlines a need to automatically test this package using GitHub Actions on pull request (PR) or pushes to the `main` branch. Adding automated tests will help observe passing or failing tests from the repository, making these findings openly informing developers or people using the package. As a side-effect, accomplishing work related to this issue will help form documented technical agreement (via source code) about how tests should be run among the maintainers (including any nuances which could be outlined in comments / docs).

I feel this should be a prerequisite of #52 in order to ensure stability of related changes. Leveraging automated tests in this way would effectively show a "before" and "after" for that issue (and others).

### PR DESCRIPTION
**Pull request by d33bs**
This PR adds automated testing for `pytest` through GitHub Actions on PR and push to the `main` branch as a prerequisite of #52. These tests have a chance of not running on this PR due to this being my first contribution to this repository (a GitHub security constraint). I've attempted to test this workflow as best as possible (manually, as attempting to use [`act`](https://github.com/nektos/act) resulted in errors related to https://github.com/actions/setup-python/issues/401).

While I was working through this I noticed there was no `CONTRIBUTING.md` or `CODE_OF_CONDUCT.md`. I've added these with some template information that has been slightly modified to meet the needs here.

Please don't hesitate to let me know if you have any questions - look forward to any feedback you may have!

Closes #53

### CODE REVIEW

**Review by miltondp — COMMENTED** [review]
Fantastic, @d33bs! Thanks for adding those missing files with the guidelines for contributing and the code of conduct. They look great. I wonder if we should enable Discussions in this project.

I'm having some internet issues on campus, so I'll try to post this comment for now and continue later.

**Comment by cgreene** [comment]
Can we add a license here? Re: #58 - somewhat time sensitive (this week would be great) as we're trying to wrap up the final progress report for this grant.

**Comment by miltondp** [comment]
Yep, we can definitely add a licence. @d33bs could you pick one suggested by Casey [here](https://github.com/manubot/manubot-ai-editor/issues/58)? The 3-clause BSD sounds like a good option.

**Comment by d33bs** [comment]
Sure thing @miltondp ! I noticed that the `setup.py` already includes a license mention: `BSD-2-Clause Plus Patent`. Should we plan to change from that license to the `BSD-3-clause`, or retain the `BSD-2-Clause Plus Patent`?

**Comment by miltondp** [comment]
Let's use what Casey suggested: `BSD-3-clause`. We might want to create another PR with the licence change and merge it quickly, so we don't rush things in this PR. Thank you, Dave!

**Review by falquaddoomi — APPROVED** [review]

**Comment by d33bs** [comment]
Thanks @miltondp and @cgreene for taking a look at this PR, thank you @falquaddoomi for the review approval! Merging this in now.

**Pull request merged**
